CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(64) NOT NULL UNIQUE,
    system_role BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE TABLE role_permissions (
    role_id BIGINT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    permission VARCHAR(64) NOT NULL,
    PRIMARY KEY(role_id, permission)
);
CREATE TABLE app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(64) NOT NULL UNIQUE,
    display_name VARCHAR(100) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE
);
CREATE TABLE user_roles (
    user_id BIGINT NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
    role_id BIGINT NOT NULL REFERENCES roles(id),
    PRIMARY KEY(user_id, role_id)
);
CREATE TABLE audit_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actor VARCHAR(64) NOT NULL,
    action VARCHAR(64) NOT NULL,
    target VARCHAR(100) NOT NULL
);
CREATE TABLE security_lock (id INTEGER PRIMARY KEY);
INSERT INTO security_lock(id) VALUES (1);
INSERT INTO roles(name, system_role) VALUES ('ADMIN', TRUE), ('AUDITOR', FALSE);
INSERT INTO role_permissions(role_id, permission)
SELECT id, 'USER_READ' FROM roles WHERE name = 'ADMIN';
INSERT INTO role_permissions(role_id, permission)
SELECT id, 'USER_WRITE' FROM roles WHERE name = 'ADMIN';
INSERT INTO role_permissions(role_id, permission)
SELECT id, 'ROLE_READ' FROM roles WHERE name = 'ADMIN';
INSERT INTO role_permissions(role_id, permission)
SELECT id, 'ROLE_WRITE' FROM roles WHERE name = 'ADMIN';
INSERT INTO role_permissions(role_id, permission)
SELECT id, 'AUDIT_READ' FROM roles WHERE name IN ('ADMIN', 'AUDITOR');
